# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20170829_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='address',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
