# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_remove_employer_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_website',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.CharField(default='', max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
