# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_auto_20170830_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, default='', upload_to='employers'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_website',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
