# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170831_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
