# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170901_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
