# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170901_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
