# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170905_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
