# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170831_1846'),
        ('employees', '0004_employee_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_on',
            new_name='application_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='cover_letter',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(default='', upload_to='resume/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
