# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20170901_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cover_letter',
            field=models.CharField(default='', max_length=17000),
        ),
    ]
