# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.FileField(default='', upload_to='cover_letters/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to='resume/%Y/%m/%d/'),
        ),
    ]
