# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_profile_photo'),
        ('candidates', '0002_auto_20170828_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AddField(
            model_name='candidate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
