# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20170831_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(default='', max_length=60),
        ),
    ]
