# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='job',
        ),
    ]
